# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeHeader', models.TextField(blank=True, default='newfasf', null=True)),
                ('codeMain', models.TextField(blank=True, default='#inclide', null=True)),
                ('pbName', models.CharField(max_length=255)),
                ('pbStat', models.TextField()),
                ('diff', models.CharField(choices=[('25', 'Easy'), ('50', 'Moderate'), ('100', 'Difficult')], default='50', max_length=4)),
                ('ips1', models.TextField(blank=True, null=True)),
                ('ips2', models.TextField(blank=True, null=True)),
                ('ips3', models.TextField(blank=True, null=True)),
                ('ips4', models.TextField(blank=True, null=True)),
                ('ops1', models.TextField(default='0')),
                ('ops2', models.TextField(default='0')),
                ('ops3', models.TextField(default='0')),
                ('ops4', models.TextField(default='0')),
            ],
        ),
    ]
